Cleo step functions offline
Next-Interactive/serverless-step-functions-offline pull request #1
Opened 2019-02-04 13:33 UTC by dahhen

2019-02-04 15:23 UTC, khadirbaaoua requested changes

2019-02-04 15:23 UTC, khadirbaaoua commented on build.js
> +            }
Je propose de réécrire plus simplement : 
```
const lambdaFunction = this.functions[variable] || this.getItemFromConfiguration(this.functions, variable);
```

2019-02-04 15:23 UTC, khadirbaaoua commented on build.js
> +            this.process(this.states[currentState.Next], currentState.Next, this.eventParallelResult);
Documenter l'inversion de ces lignes

2019-02-04 15:23 UTC, khadirbaaoua commented on parse.js
> +            return collection[name];
c'est pas grave si on ne retourne rien ? ce serait bien de retourner null ou undefined pour être plus explicite

2019-02-04 15:36 UTC, khadirbaaoua approved these changes

2019-02-04 16:42 UTC, davidclochard reviewed
Code : OK

2019-02-05 16:16 UTC, VySellathurai approved these changes
code ok

2019-02-05 16:17 UTC, merged